[project]
name = "arrowredis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.70",
    "botocore>=1.40.70",
    "numpy>=2.3.4",
    "pyarrow>=22.0.0",
    "redis>=7.0.1",
    "tqdm>=4.66.0",
    "uvloop>=0.22.1",
]
